# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'pim/kmime': '@same'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'

Options:
 require-passing-tests-on: ['Linux', 'FreeBSD']
 allow-failing-tests-on: ['Windows']
 tests-run-in-parallel: True
